format = """
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_status\
$directory\
$package\
$python\
$line_break\
$character\
"""

[character]
success_symbol = '[\$](bold white) '
error_symbol = '[x](bold red) '

[hostname]
ssh_only = false
format = '[$hostname]($style) '

[conda]
format = '[$symbol$environment](dimmed green) '
